# Copyright 2022 by Artem Ustsov

on: push

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WORKING DIRECTORY
        run: pwd

      - name: INSTALL PIP
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          which python3
          which pip

      - name: INSTALL PEP8
        run: |
          sudo pip3 install pep8-naming

      - name: INSTALL BLACK
        run: |
          sudo pip3 install black
